name = "acquisition-arena"
compatibility_date = "2024-08-15"

# Modern static assets support (no KV needed)
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[env.production]
name = "acquisition-arena-prod"
route = { pattern = "acquisition-arena.crafted.app/*", zone_name = "crafted.app" }

[env.production.vars]
VITE_API_URL = "https://api-acquisition-arena.crafted.app"

# VITE_CLERK_PUBLISHABLE_KEY will be set as a secret via CLI
