models: true
routes: false
position_in_class: after
position_in_test: after
position_in_fixture: after
position_in_factory: after
position_in_serializer: after
show_foreign_keys: true
show_complete_foreign_keys: false
show_indexes: true
simple_indexes: false
include_version: false
exclude_tests: true
exclude_fixtures: true
exclude_factories: true
exclude_serializers: true
exclude_scaffolds: true
exclude_controllers: true
exclude_helpers: true
hide_limit_column_types: "integer,bigint,boolean"
hide_default_column_types: "json,jsonb,hstore"
format_bare: true
format_rdoc: false
format_yard: false
format_markdown: false
sort: false
force: false
frozen: false
classified_sort: true
with_comment: true